#!/bin/sh
usage() {
	echo "USAGE:	$0 font-family [color-up] [color-dn] [word] [fontname]"; exit 1;
}
# This script is relased under CC0.
## SAMPLE:
# ./mksvgspcimen.sh Iosevka \#8888ff black "  [ˈmæs.tɚ]" > Iosevka_todo_topath.svg
font_family=$1
color_up=${2:-white}
color_dn=${3:-black}
word=${4:-Lorem Ipsum}
fontname=${5:-${font_family}}

cat >&2 <<EOF
mksvgspeciman 0.1

CMDLINE	$(printf '%q ' "$0" "$@")
FAMILY	${font_family}
NAME	${fontname}
UP	${color_up}
DN	${color_dn}
WORD	${word}
EOF

[ "$1" ] || usage

cat <<EOF
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<svg xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#' xmlns='http://www.w3.org/2000/svg' height='500' width='400' version='1.1' viewBox='0 0 400 500'>
	<g style='font-family: &quot;${font_family}&quot;;' xml:space='preserve'>
		<rect id='r-up' height='300' width='400' y='0' x='0' fill='${color_up}'/>
		<g id='up' fill='black'>
			<text font-size='74.667px' y='75' x='20'>${fontname}</text>
			<text font-size='192px' y='219' x='380' style='text-align:end;text-anchor:end;'>A</text>
			<text font-size='64px' y='145' x='20'>Aa Ee Rr</text>
			<text font-size='64px' y='210' x='20' style='font-style: italic'>Bb Gg Jj</text>
			<text font-size='42.667px' y='270' x='20'>${word}</text>
		</g>
		<rect id='r-dn' height='200' width='400' y='300' x='0' fill='${color_dn}'/>
		<g id='dn' fill='white'>
			<text font-size='42.667px' y='355' x='20'>
				<tspan>abcdefghijklm</tspan>
				<tspan x='20' dy='45'>nopqrstuvwxyz</tspan>
			</text>
			<text font-size='42.667px' y='455' x='20'>0123456789</text>
		</g>
	</g>
</svg>
<!-- Generated by mksvgspeciman
     https://github.com/Artoria2e5/misc/blob/master/mksvgspecimen.sh -->
EOF

_ret=$?
if [ $_ret == 0 ]; then
	echo "Done. Convert the text to paths and do other necessary adjustments in your svg editor.">&2
else
	echo "cat:	$_ret"
fi
